######################################################################
# Automatically generated by qmake (2.01a) ?? 10. ??? 00:37:28 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qtc-gdbmacros
INCLUDEPATH += .


# Input
HEADERS += unicod.h window.h 
SOURCES += main.cpp window.cpp
